name: Build on push

permissions:
  packages: write

on:
  push:
    branches:
      - main

jobs:
  build-amd64:
    name: Build image (AMD64)
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set env variables
        run: |
          echo "BRANCH=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')" >> $GITHUB_ENV
          IMAGE_NAME="${GITHUB_REPOSITORY#*/}"
          echo "IMAGE_NAME=${IMAGE_NAME//docker-/}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker buildx action
        uses: docker/setup-buildx-action@v2

      - name: Run Docker buildx
        run: |
                docker buildx build \
                --platform linux/amd64 \
                --tag ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:$BRANCH-amd64 \
                --output "type=registry" ./
  build-arm64:
    name: Build image (ARM64)
    runs-on: self-hosted

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set env variables
        run: |
          echo "BRANCH=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')" >> $GITHUB_ENV
          IMAGE_NAME="${GITHUB_REPOSITORY#*/}"
          echo "IMAGE_NAME=${IMAGE_NAME//docker-/}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Run Docker buildx
        run: |
                docker buildx build \
                --platform linux/arm64 \
                --network host \
                --tag ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:$BRANCH-arm64 \
                --output "type=registry" ./

  create-manifest:
    name: Create two-architecture manifest
    runs-on: ubuntu-20.04
    needs:
      - build-amd64
      - build-arm64

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set env variables
        run: |
          echo "BRANCH=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')" >> $GITHUB_ENV
          IMAGE_NAME="${GITHUB_REPOSITORY#*/}"
          echo "IMAGE_NAME=${IMAGE_NAME//docker-/}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create final manifest
        run: ./create-manifest.sh "ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME}" "${BRANCH}"
